version: '3.5'

services:
  consignment:
    build: ./shippy-service-consignment
    depends_on:
      - vessel
      - datastore
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  vessel:
    build: ./shippy-service-vessel
    ports:
      - 50052:50051
    environment:
      MICRO_SERVER_ADDERSS: ":50051"

  # Commands
  cli:
    build: ./shippy-cli-consignment

  datastore:
    image: mongo
    container_name: "datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017
    command: mongod --logpath=/dev/null